dhillon_lyrics_json = [
    {
        "title": "Insane",
        "singer": ["AP Dhillon", "Gurinder Gill", "Shinda Kahlon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Eh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEhna ne jhali kar jana lokan vich kalli kar jana\r\nsatt tetho jar kithe honi bin peeteya talli kar jana\r\nhusan tere toh ne haare karan nu firde ne kaare\r\ngallan vich gal tu taali ja\r\nna sun na keh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nkanu chobran toh dardi ishaare phire kardi\r\nni vekh vekh tenu meri hikk jandi khardi\r\nni mundeya de dilan utte bijli ae vardi\r\nni chann vali chan ni vi tere agge hardi\r\nbaawle hoye paye ne taare\r\ntod tera labhde bichaare\r\nnazar na lag je duniya di\r\nmere kole beh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nNi mann ja gal tu meri\r\naag ji laat kalli kairi\r\nbacha ke rakh lavan tenu\r\nkite na kar devi deri\r\nlabh de firde aa chaare\r\nhigh hoye paye ne paare\r\nni sab tere naam karan nu firde\r\njo kuj hai\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh\r\n\r\nEh munde pagal ne saare\r\ngallan vaddiyan vadde laare\r\numar di hauli adhiye tu\r\nni bach ke reh",
        "video_link": "https://www.youtube.com/watch?v=cqP8I5aaud8"
    },
    {
        "title": "Toxic",
        "singer": ["AP Dhillon"],
        "lyricist": ["Rajan Lahoria"],
        "lyrics": "\r\n    O chobbran de kaalje machaundi vaar vaar\r\n    mundeya da vairi teekha nakk hathyaar\r\n    Gal vaali gaani sohne yaar di nishani\r\n    jatti chum chum hikk naal laayi firdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    O seene aali ghaat puri kare billi akh\r\n    maut de saudagran di maar chaddi matt tu\r\n    Keel ne nu kaala tainu jachda ae baahla\r\n    Dil Thoddi utte billo aa machaayi firdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    Magnum rakha hathi faddan red rose\r\n    Court vich mundeya da vajjda si boss\r\n    Magnum rakha hathi faddan red rose\r\n    Court vich gundeya da vajjda si boss\r\n    Din ki ae raatan dekh hon vaardatan laindi\r\n    pind di mandeer piche laayi phirdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    Nakhra Nawabi koi karu barbaadi\r\n    Sahiban aale lashna te aayi phiridi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n    O lagda ae vailiyan nu saadh ja banau\r\n    kuddi saana jahe jatt piche laayi phirdi\r\n",
        "video_link": "https://www.youtube.com/watch?v=7v0_uipNGao"
    },
    {
        "title": "Saada Pyaar",
        "singer": ["AP Dhillon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "O saada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\njera kal puchya si mai haal tera\r\nsanga ne rangya chehra laal tera\r\nteriyan fikran ch langhya pura saal mera\r\ncharhde sooraj nal aaunda si khyaal tera\r\nna shak hoya ke dooriyan aan paingiya\r\njad katheya thoda ho chir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\nMainu keh roke gal ho rahi na\r\npata kinj lagu je gal muho kahi na\r\ndil tere te lakeer metho vahi na\r\ngussa doha ne si kita kal sabar nal sahi na\r\nroshni dikha ke ethe aan khalote aa\r\njithe dil eh gaman de nal ghir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\nRete vicho das hun tenu kinj labhiye\r\ndil jazbaat hun kinj das dabiye\r\ntenu door kite aala akk kinj chabiye\r\ndil kaada dil eh gamaa aali dabbi ae\r\nbharm bhulekhe sab mere door kite aa \r\nshinde aashiq waade to fir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda\r\nsaada pyaar edan da si ho gya\r\njida unglan cho reta gir janda",
        "video_link": "https://www.youtube.com/watch?v=L6fr053Z_pU"
    },
    {
        "title": "Hustlin",
        "singer": ["AP Dhillon"],
        "lyricist": ["AP Dhillon"],
        "lyrics": "O jatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae\r\n\r\nO jatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae\r\n\r\nRob jatt da ae nira tabahi nakhro\r\n24 ghante yaar rehnda tera high nakhro\r\nnit navi bhaal da ladai nakhro\r\npar tere te marda ae\r\njatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae\r\n\r\nO jatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae\r\n\r\njehde karde aa saada saatho kar len de\r\nDhillon de against gallan kar len de\r\nni mere gaane nu speed beeba fad len de\r\nsaale sidhe kar du ae\r\n\r\nO jatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae\r\n\r\nO jatt hustlin karda ae\r\nkhaab roj nave fadh da ae\r\nparvaah na karda ae",
        "video_link": "https://www.youtube.com/watch?v=x7CQk79BQTE"
    },
    {
        "title": "Fake",
        "singer": ["AP Dhillon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Hass hass laiyan ro ro tuttiyan\r\nunglan vicho unglan chhutiyan \r\nni kithe gaye vaade tere\r\nlaare sab fake mainu\r\nchadd gayo vich adhkaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\nmere utte mitheya haq vi jataunda c\r\ntaareya de naal chann jholi vich paunda c\r\nmere utte mitheya haq vi jataunda c\r\ntaareya de naal chann jholi vich paunda c\r\nni meethe hun bol tere zehar lagde ne \r\ntahio gal gal utte takrar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\nasi kita dil to dimag nal la gaya ae\r\nchamm deya bhukheya dil saada kha gea ae\r\nasi kita dil to dimag nal la gaya ae\r\nchamm deya bhukheya dil saada kha gea ae\r\nmai ta akk gaiyan hun hor labh le tu\r\nkar layi husan vapaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\njhoothe jahe hasse ne tan \r\ndukh hi ni dite mainu\r\nkato kita tere naal pyaar\r\nHass hass laiyan ro ro tuttiyan\r\nunglan vicho unglan chhutiyan",
        "video_link": "https://www.youtube.com/watch?v=FkgAdHM_kCk"
    },
    {
        "title": "Arrogant",
        "singer": ["AP Dhillon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Ho desi munde kude aa nadale val de\r\nduniya ae ghumi na tu jaani kal de\r\nje tu versace aa pasand kardi\r\nsaanu nehde la la asi gucci set aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\nApna jo area vo border ke paas hai\r\nchemicals bhi milte hai aur milti bhi ghaas hai\r\ndhokha na karenga aur na hi koi chance hai\r\nakad se rehte hai yahi toh romance hai\r\nyahi toh romance hai\r\nO yahi toh romance hai\r\nMan yahi toh romance hai\r\nunj ghoor nal chehreyan toh rang uda diye\r\ntu gal kar jind tere naave laa diye\r\nkise de khyalan nal kita na play\r\nje koi saade jor paave fer paunde bend aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa",
        "video_link": "https://www.youtube.com/watch?v=UkOPtbo73Ws"
    },
    {
        "title": "Drip",
        "singer": ["AP Dhillon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Munde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nSleeve pant nal off white\r\ngal te diamond te tuki site\r\nshaam payi te dakke si daaru\r\nna van sharoness kiti flight\r\nfiner jatt nu phone si laaya\r\nte ode kolo chuki laal ji raari\r\nraari raari raari raari\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nKame te garso eko ji ghadi je yaar aa\r\nSharu faraar aa majhe de munde vi chaar aa\r\ngabbe aa munde nede na aa ji\r\nkarna jayi kalli te kehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri\r\nMunde aa pind de drip aa zehri",
        "video_link": "https://www.youtube.com/watch?v=XHPSxtLCloY"
    },
    {
        "title": "Chances",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Tenu pyaar das mai kara k nai\r\nis dil nu fer samjhavan mai\r\nsaade dil da boota qabool ae k nai\r\nja kise hor baggi ch lava mai\r\naukhi aa satt ji jarni\r\nbas gal tere naal si karni\r\nsaara kuj aap dekhda\r\nbas tu si haami bharni\r\nchah vi ne tutt ge saade\r\ntutt gaye aa dil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nPahadon disda shehar ni\r\nhoni si dhali dopahre \r\nsooraj da rang kesari\r\nrang tera karda kehar ni\r\njera tera haath ja fad ke\r\njatt janda khil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nRete te tenu vaaunda\r\ngin de asi challa ni\r\ntaareya di chhat de thale\r\nkar de aapa gallan ni\r\nwine si laini mehngi\r\ncup honde fill kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nDil tere naal kholan mai\r\nhaye ni bas sach hi bolan mai\r\ntere jini sohni dekhi na\r\nhor kithe kithe tolan mai\r\ndekhi na bhar di alahde \r\nakhaan vich sil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude\r\nkini tu sohni aa ni\r\ndasda tenu mil kude",
        "video_link": "https://www.youtube.com/watch?v=NhgQVF4WvyI"
    },
    {
        "title": "GOAT",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Rajan Lahoria"],
        "lyrics": "O choti umar toh jehde rakhe aa ni paal\r\nDur tak jaane shonk mitran de naal\r\nOld ne weapon te old ne vichaar\r\nreejan nal rakhe aa sambhal sohniye\r\nClassy je drip naale whip de shokeen\r\nkhule aa sabah billo khuli aa zameen\r\nna neetan vich khot jatt de\r\nbhare pocketan ch note jatt de\r\nGoriye \r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye\r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye\r\nCheeneya di jodi naal ghodiyan ne chaar\r\nRemington rifle nal khed de shikaar\r\nlagdi aa khuli fer bet sohniye\r\ncheez dil nu jo lagge jhatt jeet lende yaar\r\nMaar dinda hikkan ni te ford da farata\r\nalahdan kawariyan vi lendiya ne jhaka\r\npatte naio jaane thode ziddi touch de\r\nakh laal kauda naagni vi chakh de\r\nGoriye\r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye\r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye\r\nO dil de fakeer shahi vajj da gharana\r\neast to west bole saada sarnaava\r\nMar mar denda jehda ohnu aa salah\r\nMaan lo baharan nal kuj vi ni jaana\r\no bombay sidha raah lag de\r\nLahoriye de geet vajde\r\nO gol na asool jagg de\r\nO chad de nu log dakk de\r\nGoriye\r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye\r\nNi yaar velly GOAT Jatt de\r\nO athre aa shonk jatt de\r\nni weapon aa load jatt de\r\nbolan vich rob jatt de \r\nGoriye",
        "video_link": "https://www.youtube.com/watch?v=dy05ncw9iGg"
    },
    {
        "title": "Takeover",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Shinda Kahlon", "AP Dhillon", "Gurinder Gill", "AR Paisley"],
        "lyrics": "Gaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nPaana cho jatt aa uthe\r\ntakhte aa karte puthe\r\nohna di fatti poch ti\r\njina de palle thude\r\nkaiyaan di goddiya hogiya\r\nkaiyaan di bediya dubiya\r\nkoi na landa chugiyan\r\njitho dii aap tare aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nFeem di dabbi kole dabb hathyaar ni\r\nnagni de vich jatt karde shikaar ni\r\nzindagi de raule baliye hass hass ke face kare aa\r\nkida koi adh ju murre shinda dhillon naal khade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nLeede ne mehnge jo paunde ne jatt te karde naaran te flex\r\nna kaam te jaiye shonk pugaiye te 31 de apne check\r\ngaddi tu dekh mili aa gift porsche aa kaali stick aa shift\r\ngas te pair track te tu aa saale sawaar bade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nHo karde aa chill par karde na dhil kite \r\nadh je garari othe la dende chhill\r\nasle di nok utte hundi badmashi hundi\r\nchobran di bentley di roz aa talaashi\r\nasi na jor laya na bhota paisa chaya\r\nakh ban ke mehnat kiti kaam apne aap sarre aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa\r\nGaddiyan de kaafle aa jeban ch note bhare aa\r\ndabbi hathyaar tange ne pistol te nag jade aa",
        "video_link": "https://www.youtube.com/watch?v=brMvIdDrOhk"
    },
    {
        "title": "Free Smoke",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["AP Dhillon", "Deep Jhanju"],
        "lyrics": "Mehnat na kaam kar agge vadh de\r\nakh naio rakhi di kise de haq te\r\no dekh ke chadai saddi pai aa industry\r\nsuttne nu saanu aa scheman labh de\r\nshonk nal kaam karde aa putt sun lo\r\nje adh je garari kanda taar dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nJhoothe na stream saade jhoothe na view\r\njhoothe naio daave saade jhoothe na kanoon\r\ngaane saade laan nu saale labh de aa queue\r\nkaro sir sutt kaam shayad gal ban jau\r\nkaan laake dove gal meri sun lao\r\nnai ta dhakke nal khane thade vaad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nJehde sarhde aa saale sab khich lo tyaari\r\nbhota time ni gavauna seep launi iko vaari\r\nsaanu kise nal ni hate saadi bol baani theth\r\nkayian nu aven aa lattan khaan di bimari\r\nkiven chakkni breath ohda iko route death\r\ntatte je blood sab thaar dende aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa\r\nlukk lukk vaar kariye na kise te\r\nsareaam vagaar putt paad dene aa",
        "video_link": "https://www.youtube.com/watch?v=cXAyRBfHM5Y"
    },
    {
        "title": "Brown Munde",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Lambo truck vich gedi sidhi hollywood\r\nGeet desi mundeya de sune bollywood\r\nMusic di wave aa naa bhalde koi fame aa\r\nTe gauna vi aaunda te lyrics ae\r\nChnge jehre chalde si kise ton na thalde si\r\nOhna da banaunde aa clown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO pepe di jean aa life haseen aa\r\nRaatan rangeen aa chobar shokeen aa\r\nCupan ch lean aa gallan to mean aa\r\nKayi naaran de message chhade kar seen aa\r\nPakke tarak aa na udh de jawak aa\r\nDaaru ch karde drown munde \r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nFordan to g class\r\nPhonean te motest karde na game lag\r\nBrown brown munde brown munde\r\nMind te beach hathan ch reach\r\nBudde hoya nu kayi kuch kita ae teach\r\nAsi karde aan apni te lokan di preach\r\nSaade aa apne contract ch ape te breach\r\nLaggi full mauj aa stir kiti sauce aa\r\nKaraunde buzz down munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\n \r\nO gutt te aa venty na notean di ginti\r\nTime saade kol aa te lok hoye anti aa\r\nYaari di guarantee aa loki kitte senti aa\r\nDuniya ae labdi te naaran vi senti aa\r\nShinde kole aaj\r\nEna kal jana la te parso nu bagan ch cash leke \r\nHone capetown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO yaar bhavein thode aa yakke hi jode aa\r\nMeethe na bande eh bullan ton kaude aa\r\nLambe hi tode aa hikkan ton chaude aa\r\nMukkdi aa gall ena dabban ch ghode aa\r\nDiamond de piece ne crore an di cheez ne\r\nHonde kithe down munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\n \r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nSir kadh gajj de speakeran ch vajde brown munde\r\nBrown munde\r\nO desi je geet aa trap ji beat aa\r\nBrown munde",
        "video_link": "https://www.youtube.com/watch?v=VNs_cCtdbPc"
    },
    {
        "title": "Droptop",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["AP Dhillon", "Gurinder Gill"],
        "lyrics": "Ho Droptop gaddiyan ch ghumde aa yaar\r\ndabb vich russian banda dendi paad\r\nethe charhde toh charhde salaaman karde\r\nmuh na tu adh thal paa dende yaar\r\nethe paya jatta gaah chune vakhre je raah\r\ngaane chartan utte charhe aaunde naio thaa\r\nkiven karenga compete kiti beat na repeat\r\ndabde ni yaar rakhe khule je sabaah\r\nkite dis ji na nede kaka town vich mere\r\nnal shooteran da tola tenu labhna ni raah\r\nkaka chadd denga gaana maarhe samme nu tu rona\r\nlangh gaya time tere haath naio aauna\r\nkiti naio copy wave navi aa chalai\r\nTere shahar vich dekh AP dhillon di charhai\r\nTere shahar vich dekh AP dhillon di charhai\r\nO kehnde jatt di garari hundi badi maarhi\r\nyaar 5 7 naal naale aakh hundi chaarhi\r\ntere shahar vich gehra saada iko hi bathera\r\nlaage lagni ni billo antiyan di taahni\r\ngal jhooth na tu jaani ae kharak ae purani\r\neh landua di taahni mure lau bande khani\r\njado hikk vicho langhi ehna mangna na paani\r\nehna mangna na paani\r\npura haddan vich jor turan sheran vali tor\r\njithe vardaat hogi oh saada hou scene \r\nrakha diggi vich asle te jebi vich feem\r\nHo Droptop gaddiyan ch ghumde aa yaar\r\ndabb vich russian banda dendi paad\r\nethe charhde toh charhde salaaman karde\r\nmuh na tu adh thal paa dende yaar\r\nethe paya jatta gaah chune vakhre je raah\r\ngaane chartan utte charhe aaunde naio thaa\r\nkiven karenga compete kiti beat na repeat\r\ndabde ni yaar rakhe khule je sabaah",
        "video_link": "https://www.youtube.com/watch?v=YINxH2VLP-A"
    },
    {
        "title": "Foreigns",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "o rakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nrakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nWindow maker de naal di ki rees\r\nvaaj nal dilan vicho kad dendi cheez\r\ntyran di tabahi jandi chadhi di aa full\r\nutto khadi hundi feem aali goli\r\no rakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nrakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nMategan da puch dekhi mull\r\nmaada taada banda kithe kar juga bhul\r\nchak chak addiyan dekhde si loki\r\njado tuhade ghar aal di mai modi\r\no rakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nrakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nPaani vangu cash munde karde flow\r\ngaddiya ne tej kaam rakhiye slow\r\nkhate jado full asi dabiye vi kyo\r\nkiti jatta aali kari di ni thodi\r\no rakhan porsche te bentley di jodi\r\no rakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nrakhan porsche te bentley di jodi\r\no rakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi\r\nrakhan porsche te bentley di jodi\r\nik ford aala sapp ik laal rangi ghodi",
        "video_link": "https://www.youtube.com/watch?v=jWz5on5N14E"
    },
    {
        "title": "Deadly",
        "singer": ["AP Dhillon"],
        "lyricist": ["AP Dhillon"],
        "lyrics": "Deadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nFame dekh dekh piche lagi duniya\r\nniveyan nu jhaak koi ni puchhda\r\nduniya tu jeetan di gal karda\r\npital nu dekh ke koi ni rukda\r\ngoliyan di laa du jhadi\r\ngun betha load kari\r\nmaut nalo pehlan ae asool jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nKaam uche kar sar neeva rakhiye\r\nmaan bhota der kade ni tikkda\r\nmehnatan di khat dil saaf rakhiye\r\njhooth na bazaar bhota chir vikkda\r\nkehnde neetan nu muraadan \r\nbanda kaane nal hila dange\r\nkite lightly na leji tu bol jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nGal muhon kadiye nu sire chaadiye\r\nnamadad bande te kade rob maariye\r\nginti de rakhe aa ni 4 5 yaar\r\nbhoti na mandeer nu sire chaadiye\r\ntera majhe cho ae yaar \r\ntahio kabbe aa vichaar\r\nhustle nal ralde aa asool jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nDeadly aa zone santaliyan ne kol\r\nbhul ke tu vad ji na shehar jattan de\r\nbhul ke tu vad ji na shehar jattan de\r\nbhul ke tu vad ji na shehar jattan de",
        "video_link": "https://www.youtube.com/watch?v=rDH0kjE6enE"
    },
    {
        "title": "Most Wanted",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Yash G"],
        "lyrics": "Ho gaddi ch gandaase muh te gaal hondi aa\r\njatt kaum toh aa karde belong ni\r\nbande khani bande kol load rehndi aa\r\nsaadi vardaat chaldi na jada long ni\r\nyaaran kol puchhengi pyaar vi bathera\r\nmere vairian toh puchhi kida sir khulde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\nmathe vich ratta ae saroor chadya\r\nseene vich sheran wala jera rakhde\r\nmauke utte fire fir ehi maarde\r\nunj dabban nal laake tan bathere rakhde\r\njidi hikk vich jor sidha aan takre\r\ndekh giddhan da kath naio pair dolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\njehda saade nal khenda oh maut sundi\r\ntime te place kaka aap chun li\r\njehde haige si faraar vardaat kar gaye\r\nnewsan utte chalugi report sun layi\r\nla li police nu phone chheti wait na kari\r\naven chakhad na chetti kite jhul de\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\nRaah jande das ki scheme launge\r\naapa soch tere kadd nalo vaddi rakhde\r\njehda baada bole ohnu chakk layi da\r\nkhaa ke tola tola feem akh khadi rakhde\r\nsurrey vich aake shareaam puch layi\r\njana khana landu aapa naio gol de\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\npeeth utte galbaat badi karde\r\nchup rehndi aa mandeer jithe jatt bolde\r\nchup rehndi aa mandeer jithe jatt bolde\r\nchup rehndi aa mandeer jithe jatt bolde",
        "video_link": "https://www.youtube.com/watch?v=OImvWUHfNo8"
    },
    {
        "title": "Majhail",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "    O gujjran de vangu dekhi taphe vajde\r\n    Protein kha kha saadiyan na deha baniya\r\n    saade nal adde gharan cho ni labne\r\n    tarika vicho labdiyan lasha gadhiyan\r\n    pehle kari di aa salam eh pakke aa asool\r\n    je add je garari boldiyan goliyan\r\n\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n\r\n    O tedha tedha takk sanu laune aa andaaze\r\n    bondle ja paniyaan ch fire jhaakda\r\n    kundiya ne mucchha sir tediyan ne pagan\r\n    saada vairi nal jod jida aa karaar da\r\n    loki sanu sir ton crack das de\r\n    bande rond bhaleya te shaklan ne bholiyan\r\n\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n\r\n    O varto zubaan di aa ghat karde\r\n    baavan vale zor nal pahad toli da\r\n    majhe de aa munde mehntan de haani\r\n    maade laake vala para asi pairi roli da\r\n    jehde bolde aa jada sab chup ho jaane\r\n    jado teen foot diiyan taad taad boliyan\r\n\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n\r\n    O janta garage shikran de val nu\r\n    vekh vekh duniya naal aayo ni\r\n    kai kadan ge galan kai laun ge scheman\r\n    par sadi vali wave tetho ride ni honi\r\n    sanu kise da bhaa sada apna ae raah\r\n    mache log kamyabi diyan aan doliyan\r\n\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n\r\n    O vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    O vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan\r\n    vair khat jatan nal bhaj naio hona\r\n    asi pittal nal kaiyan diya hikka kholiyan",
        "video_link": "https://www.youtube.com/watch?v=yzIyufV6ADk"
    },
    {
        "title": "Excuses",
        "singer": ["AP Dhillon", "Gurinder Gill"],
        "lyricist": ["AP Dhillon", "Gurinder Gill"],
        "lyrics": "Mere dil naal laare ni tu laun waliye\r\nDil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan\r\n\r\nTutte dil nu saambhi firde ki fayda muttyaare ni\r\nbarah saal majhiyan charayiaa chadde takht hazare ni\r\nhar saah naal yaad tenu karde rahe\r\nKoi saade vangu karuga tan pata laguga\r\nDil naal laare ni tan laon walye Dil tera jado tuttuga\r\n\r\nMere dil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan\r\n\r\nKehndi hondi sii chann tak raah bana de\r\ntaare ne pasand  mainu hethaann saare laatee\r\nOna taareya de vich jado mainu vekhengi\r\nMeri yaad jad aaugi tan pata laguga\r\n\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\n\r\nRaas na aaya tenu ni jo dil da mehal banaya si\r\ntod ke bodi phullan de os mehal ch buta laaya sii\r\nNi jiven saanu chadd gai aa ni tu alahde\r\nJado tenu koi chaduga tan\r\nO jiven saanu chadd gai aa ni tu alahde\r\n\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\n\r\nIshqan de raahan vich rul ke re gaye aan\r\nLokan dite taane mene has ke seh gaye aa\r\nIshqan de raahan vich rul ke re gaye aan\r\nLokan dite taane mene has ke seh gaye aa\r\nSaade pyaar nu tu pairan thale roldi rahi\r\njazbaat jado rule odo pata laguga\r\n\r\ndil naal laare ni tu laun waliye\r\ndil tera jado tuttuga tan pata laguga\r\ndil naal laare ni tu laun waliye\r\n\r\nDil tera jado tuttuga tan pata laguga",
        "video_link": "https://www.youtube.com/watch?v=vX2cDW8LUWk"
    },
    {
        "title": "Arrogant",
        "singer": ["AP Dhillon"],
        "lyricist": ["Shinda Kahlon"],
        "lyrics": "Ho desi munde kude aa nadale val de\r\nduniya ae ghumi na tu jaani kal de\r\nje tu versace aa pasand kardi\r\nsaanu nehde la la asi gucci set aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\nApna jo area vo border ke paas hai\r\nchemicals bhi milte hai aur milti bhi ghaas hai\r\ndhokha na karenga aur na hi koi chance hai\r\nakad se rehte hai yahi toh romance hai\r\nyahi toh romance hai\r\nO yahi toh romance hai\r\nMan yahi toh romance hai\r\nunj ghoor nal chehreyan toh rang uda diye\r\ntu gal kar jind tere naave laa diye\r\nkise de khyalan nal kita na play\r\nje koi saade jor paave fer paunde bend aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa\r\ndil de aa maum aadtan ne kabbiyan\r\nthode je aa rude thode arrogant aa",
        "video_link": "https://www.youtube.com/watch?v=UkOPtbo73Ws"
    }
]
